Revert "Editorial: Explicitly enable MDN Panels"
This reverts commit 6e9115a443dc9354b9b952809cbae0b2a73f534a.

Causing build to fail on github with:

  FATAL ERROR: Couldn't find the MDN data for 'indexeddb-3' nor 'indexeddb'.